// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FluttefrFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMBtQJ2hs9-Rh9EstbPJ6FA-Vk4nY-gpg',
    appId: '1:1053940310558:web:45b248913e2947e058c40f',
    messagingSenderId: '1053940310558',
    projectId: 'wisensor-app-6',
    authDomain: 'wisensor-app-6.firebaseapp.com',
    storageBucket: 'wisensor-app-6.appspot.com',
    measurementId: 'G-XZL46P2FNC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKofKXiAUzYXCyQ4s0xQNSckXp4Sozhvc',
    appId: '1:1053940310558:android:7de10a15cffc0b2958c40f',
    messagingSenderId: '1053940310558',
    projectId: 'wisensor-app-6',
    storageBucket: 'wisensor-app-6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO4YJVg5pGIB89nZhMnbjNzbSM3hXQBTU',
    appId: '1:1053940310558:ios:79e898191dd285fa58c40f',
    messagingSenderId: '1053940310558',
    projectId: 'wisensor-app-6',
    storageBucket: 'wisensor-app-6.appspot.com',
    iosClientId: '1053940310558-r6gk2hfrdqgui5ved3gj519m7hi6h8fo.apps.googleusercontent.com',
    iosBundleId: 'com.example.wisensorApp6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO4YJVg5pGIB89nZhMnbjNzbSM3hXQBTU',
    appId: '1:1053940310558:ios:f3abf727d9d92e8558c40f',
    messagingSenderId: '1053940310558',
    projectId: 'wisensor-app-6',
    storageBucket: 'wisensor-app-6.appspot.com',
    iosClientId: '1053940310558-l07is87cubmh7rotptfipuuodlcr031f.apps.googleusercontent.com',
    iosBundleId: 'com.example.wisensorApp6.RunnerTests',
  );
}
